baseURL = "https://wasim.co/"
languageCode = "en-us"
title = "Wasim Ullah"
googleAnalytics = "UA-129037953-1"
tags = ["wasim", "wasim ullah", "ullah", "digital marketing", "online marketing", "graphic design", "sales funnel", "social media marketing", "search engine optimization", "video editing", "email marketing", "social media advertising", "search engine advertising", "content writing", "blogging", "growth hacking", "content marketing", "lessons"]

[params]
	name = "Wasim Ullah"
	description = "Read opinion based articles and curated content on anything related to marketing, design, and coding."

[author]
	author = "Wasim Ullah"
	bio = "Marketer"

	twitter = "mrwullah"
	facebook = "mrwullah"

	enableRSS = true
	enableToc = true

	enableDisqus = false
	disqusShortname = "WasimU"

	enableSummary = true
	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = true


	enableGoogleAnalytics = true
	enableBaiduAnalytics = false
	# Set the value to your baidu analysis code if you want to use baidu analytics
	baiduAnalytics = 'your_baidu_analysis_code'

	enableRobotsTXT = true
	canonifyURLs = true

	enableTwitterCard = true
	# The url for twitter card image, default is avatar.png in static/images directory
	twitterCardImage = "https://wasim.blog/images/man.jpg"

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	archive = ""
	blog = ""
	subscribe = ""

	olderPosts = ""
	newerPosts = ""
	copyright = ""

	# show latest posts in single page
	showLatestPosts = true
	readMore = ""

	# Share
	enableShare = false
	tweet = ""
	share = ""

	# 404 page
	title404 = "Page 404"
	subtitle404 = "Come again? Or else."
	
	# Sharing options and author information in posts
	aboutAuthor = "Marketer"

iconFont = "font-awesome"
socialIconStyle = ""

[social]
linkedin-square = "https://www.linkedin.com/in/mrwullah"
facebook-square = "https://www.facebook.com/mrwullah"
