baseURL = "/"
languageCode = "en-us"
title = "Wasim Ullah"
googleAnalytics = "UA-129037953-1"

[params]
	name = "Wasim Ullah"
	description = "Read opinion based articles and curated content on anything related to marketing, design, and coding."

	twitter = "mrwullah"
	facebook = "mrwullah"

	enableRSS = true
	enableToc = true

	enableDisqus = false
	disqusShortname = "WasimU"


	enableSummary = true
	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = true


	enableGoogleAnalytics = true
	enableBaiduAnalytics = false
	# Set the value to your baidu analysis code if you want to use baidu analytics
	baiduAnalytics = 'your_baidu_analysis_code'

	enableTwitterCard = false
	# The url for twitter card image, default is avatar.png in static/images directory
	twitterCardImage = ""

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	archive = ""
	subscribe = ""

	olderPosts = ""
	newerPosts = ""
	copyright = ""

	# show latest posts in single page
	showLatestPosts = false
	readMore = ""

	# Share
	enableShare = false
	tweet = ""
	share = ""

	# 404 page
	title404 = ""
	subtitle404 = ""
	
	# Sharing options and author information in posts
	aboutAuthor = "Seller."

iconFont = "mono-social"
socialIconStyle = ""

[social]
circlelinkedin = "https://www.linkedin.com/in/mrwullah"
