baseURL = "/"
languageCode = "en-us"
title = "Wasim Ullah"
googleAnalytics = "UA-129037953-1"

iconFont = "mono-social"
socialIconStyle = ""

[social]
circlelinkedin = "https://www.linkedin.com/in/mrwullah"
